### PR TITLE
fix mousewheel and sourcemap file

### PR DESCRIPTION
**Pull request by cgestes**

### CODE REVIEW

**Comment by cgestes** [comment]
ping

**Comment by cgestes** [comment]
(this is merged in vispy btw)

**Comment by larsoner** [comment]
@rossant you on this one?

**Comment by rossant** [comment]
@Eric89GXL yep I'll review soon

**Comment by cgestes** [comment]
master broken without that 2 lines commit. can you click on 'merge'.

this commit has already been reviewed in vispy.

**Pull request merged**
