### PR TITLE
allow passing a canvas as texture data

### PR DESCRIPTION
**Pull request by almarklein**

### CODE REVIEW

**Comment by almarklein** [comment]
Like, render stuff to a 2D context, and then include that drawing in a gl context.

**Comment by almarklein** [comment]
ping: can @rossant or someone else please have a look? I need this :)

**Comment by larsoner** [comment]
Looks backward-compatible to me, @rossant please take a look and I'm sure @almarklein will fix any problems after I merge :)

**Comment by rossant** [comment]
sorry for the delay, I don't have much time right now... @almarklein @Eric89GXL @cgestes feel free to merge without me for now. thanks!

**Comment by cgestes** [comment]
can't help, I dont understand the code.

**Comment by almarklein** [comment]
Thanks

**Pull request merged**
